primary_menu:
  items:
    - title: Images
      url: "/assets/images"
    - title: kollektionen
      url: "#"
    - title: shop
      url: "#"
      icon: arrow-up
    - title: kontakt
      url: "#"
